-- Session-bound Adapter credentials. Raw ticket material is generated by an Adapter and never
-- crosses this schema boundary; the Hub persists only a SHA-256 digest and immutable provenance.

CREATE TABLE adapter_session_tickets (
  id TEXT PRIMARY KEY CHECK(id GLOB 'stk_[A-Za-z0-9_-]*'),
  bundle_id TEXT NOT NULL CHECK(bundle_id GLOB 'stb_[A-Za-z0-9_-]*'),
  purpose TEXT NOT NULL CHECK(purpose IN ('CONTROL', 'MODEL_MCP', 'CAPTURE', 'INJECTOR')),
  token_sha256 TEXT NOT NULL UNIQUE CHECK(
    length(token_sha256) = 64
    AND token_sha256 = lower(token_sha256)
    AND token_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  offered_by_auth_credential_id TEXT REFERENCES auth_credentials(id) ON DELETE RESTRICT,
  offered_by_ticket_id TEXT REFERENCES adapter_session_tickets(id) ON DELETE RESTRICT,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  adapter_client TEXT NOT NULL CHECK(adapter_client IN ('codex', 'claude')),
  agent_id TEXT NOT NULL CHECK(agent_id = adapter_client),
  session_client TEXT NOT NULL CHECK(session_client IN (
    'codex-app-server', 'codex-cli-hooks', 'claude-channel', 'claude-hooks'
  )),
  role TEXT NOT NULL CHECK(role IN ('primary', 'reviewer', 'observer')),
  transport TEXT NOT NULL CHECK(transport IN ('websocket', 'hook-poll')),
  delivery_mode TEXT NOT NULL CHECK(delivery_mode IN (
    'native_channel', 'app_server_push', 'hook_poll', 'mailbox_only'
  )),
  external_session_id TEXT,
  external_thread_id TEXT,
  run_id TEXT NOT NULL,
  activation_mode TEXT NOT NULL CHECK(activation_mode IN (
    'FIRST_LINEAGE', 'CURRENT_HEAD_REPLACEMENT', 'MANAGED_RESERVATION', 'SESSION_AUXILIARY'
  )),
  expected_lineage_id TEXT REFERENCES session_lineages(id) ON DELETE RESTRICT,
  expected_head_session_id TEXT REFERENCES agent_sessions(id) ON DELETE RESTRICT,
  launch_reservation_id TEXT REFERENCES session_launch_reservations(id) ON DELETE RESTRICT,
  hub_session_id TEXT REFERENCES agent_sessions(id) ON DELETE RESTRICT,
  lineage_id TEXT REFERENCES session_lineages(id) ON DELETE RESTRICT,
  incarnation INTEGER CHECK(
    incarnation IS NULL OR (typeof(incarnation) = 'integer' AND incarnation > 0)
  ),
  idempotency_key TEXT NOT NULL,
  request_sha256 TEXT NOT NULL CHECK(
    length(request_sha256) = 64
    AND request_sha256 = lower(request_sha256)
    AND request_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  state TEXT NOT NULL CHECK(state IN ('PENDING', 'ACTIVE', 'REVOKED', 'EXPIRED', 'SUPERSEDED')),
  offer_expires_at TEXT NOT NULL CHECK(
    unixepoch(offer_expires_at) IS NOT NULL
    AND offer_expires_at = strftime('%Y-%m-%dT%H:%M:%fZ', offer_expires_at)
  ),
  expires_at TEXT CHECK(
    expires_at IS NULL OR (
      unixepoch(expires_at) IS NOT NULL
      AND expires_at = strftime('%Y-%m-%dT%H:%M:%fZ', expires_at)
    )
  ),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  activated_at TEXT,
  terminal_at TEXT,
  terminal_reason TEXT,
  UNIQUE(bundle_id, purpose),
  CHECK((offered_by_auth_credential_id IS NULL) <> (offered_by_ticket_id IS NULL)),
  CHECK(
    (activation_mode = 'FIRST_LINEAGE'
      AND expected_lineage_id IS NULL
      AND expected_head_session_id IS NULL
      AND launch_reservation_id IS NULL)
    OR (activation_mode = 'CURRENT_HEAD_REPLACEMENT'
      AND expected_lineage_id IS NOT NULL
      AND expected_head_session_id IS NOT NULL
      AND launch_reservation_id IS NULL)
    OR (activation_mode = 'MANAGED_RESERVATION'
      AND expected_lineage_id IS NOT NULL
      AND launch_reservation_id IS NOT NULL)
    OR (activation_mode = 'SESSION_AUXILIARY'
      AND expected_lineage_id IS NOT NULL
      AND expected_head_session_id IS NOT NULL
      AND launch_reservation_id IS NULL)
  ),
  CHECK(
    (state = 'PENDING'
      AND hub_session_id IS NULL AND lineage_id IS NULL AND incarnation IS NULL
      AND expires_at IS NULL AND activated_at IS NULL
      AND terminal_at IS NULL AND terminal_reason IS NULL)
    OR (state = 'ACTIVE'
      AND hub_session_id IS NOT NULL AND lineage_id IS NOT NULL AND incarnation IS NOT NULL
      AND expires_at IS NOT NULL AND activated_at IS NOT NULL
      AND terminal_at IS NULL AND terminal_reason IS NULL)
    OR (state IN ('REVOKED', 'EXPIRED', 'SUPERSEDED')
      AND terminal_at IS NOT NULL AND terminal_reason IS NOT NULL
      AND (
        (hub_session_id IS NULL AND lineage_id IS NULL AND incarnation IS NULL
          AND expires_at IS NULL AND activated_at IS NULL)
        OR (hub_session_id IS NOT NULL AND lineage_id IS NOT NULL
          AND incarnation IS NOT NULL AND expires_at IS NOT NULL AND activated_at IS NOT NULL)
      ))
  )
);

CREATE INDEX idx_adapter_session_tickets_digest_state
  ON adapter_session_tickets(token_sha256, state, offer_expires_at, expires_at);
CREATE INDEX idx_adapter_session_tickets_binding
  ON adapter_session_tickets(hub_session_id, purpose, state);
CREATE INDEX idx_adapter_session_tickets_lineage
  ON adapter_session_tickets(lineage_id, incarnation, purpose, state);
CREATE UNIQUE INDEX ux_adapter_session_ticket_auth_idempotency
  ON adapter_session_tickets(offered_by_auth_credential_id, idempotency_key)
  WHERE offered_by_auth_credential_id IS NOT NULL;
CREATE UNIQUE INDEX ux_adapter_session_ticket_ticket_idempotency
  ON adapter_session_tickets(offered_by_ticket_id, idempotency_key)
  WHERE offered_by_ticket_id IS NOT NULL;

CREATE TRIGGER adapter_session_tickets_digest_collision
BEFORE INSERT ON adapter_session_tickets
WHEN EXISTS (
  SELECT 1 FROM auth_credentials credential
  WHERE credential.token_sha256 = NEW.token_sha256
)
BEGIN
  SELECT RAISE(ABORT, 'TICKET_DIGEST_COLLISION');
END;

CREATE TRIGGER adapter_session_tickets_pending_only_insert
BEFORE INSERT ON adapter_session_tickets
WHEN NEW.state <> 'PENDING'
BEGIN
  SELECT RAISE(ABORT, 'TICKET_NOT_PENDING');
END;

CREATE TRIGGER adapter_session_tickets_client_mode_guard
BEFORE INSERT ON adapter_session_tickets
WHEN NEW.activation_mode = 'SESSION_AUXILIARY'
  AND NEW.session_client IN ('codex-cli-hooks', 'claude-hooks')
BEGIN
  SELECT RAISE(ABORT, 'TICKET_BINDING_MISMATCH');
END;

-- Every state change must be opened by the Hub's connection-local bundle transition guard.
-- A direct SQL caller either has no registered function (fail closed) or receives zero here.
CREATE TRIGGER adapter_session_tickets_guarded_state_transition
BEFORE UPDATE OF state ON adapter_session_tickets
WHEN OLD.state <> NEW.state
  AND crossagent_session_ticket_transition_guard(NEW.bundle_id, OLD.state, NEW.state) <> 1
BEGIN
  SELECT RAISE(ABORT, 'TICKET_BUNDLE_TRANSITION_REQUIRED');
END;

CREATE TRIGGER auth_credentials_ticket_digest_collision
BEFORE INSERT ON auth_credentials
WHEN EXISTS (
  SELECT 1 FROM adapter_session_tickets ticket
  WHERE ticket.token_sha256 = NEW.token_sha256
)
BEGIN
  SELECT RAISE(ABORT, 'TICKET_DIGEST_COLLISION');
END;

CREATE TRIGGER adapter_session_tickets_offer_authority
BEFORE INSERT ON adapter_session_tickets
WHEN NOT (
  (
    NEW.offered_by_ticket_id IS NULL
    AND (
      (NEW.purpose IN ('CONTROL', 'MODEL_MCP')
        AND NEW.offered_by_auth_credential_id = 'crd_agent_' || NEW.adapter_client)
      OR (NEW.purpose = 'CAPTURE'
        AND NEW.offered_by_auth_credential_id = 'crd_capture_' || NEW.adapter_client)
      OR (NEW.purpose = 'INJECTOR'
        AND NEW.offered_by_auth_credential_id = 'crd_inject_' || NEW.adapter_client)
    )
    AND EXISTS (
      SELECT 1
      FROM auth_credentials credential
      JOIN auth_principals principal ON principal.id = credential.principal_id
      WHERE credential.id = NEW.offered_by_auth_credential_id
        AND credential.revoked_at IS NULL
        AND (credential.expires_at IS NULL
          OR unixepoch(credential.expires_at) > unixepoch(NEW.created_at))
        AND principal.status = 'ACTIVE'
        AND principal.client_type = NEW.adapter_client
    )
  )
  OR (
    NEW.offered_by_auth_credential_id IS NULL
    AND NEW.purpose IN ('CONTROL', 'MODEL_MCP')
    AND NEW.activation_mode IN ('CURRENT_HEAD_REPLACEMENT', 'SESSION_AUXILIARY')
    AND EXISTS (
      SELECT 1
      FROM adapter_session_tickets offerer
      JOIN agent_sessions session ON session.id = offerer.hub_session_id
      JOIN session_lineages lineage ON lineage.id = offerer.lineage_id
      WHERE offerer.id = NEW.offered_by_ticket_id
        AND offerer.purpose = 'CONTROL'
        AND (
          (offerer.state = 'ACTIVE'
            AND unixepoch(offerer.expires_at) > unixepoch(NEW.created_at))
          OR (
            NEW.activation_mode = 'CURRENT_HEAD_REPLACEMENT'
            AND (
              (offerer.state = 'EXPIRED'
                AND offerer.terminal_at IS NOT NULL
                AND offerer.terminal_reason IS NOT NULL
                AND NOT EXISTS (
                  SELECT 1 FROM adapter_session_tickets bundle_peer
                  WHERE bundle_peer.bundle_id = offerer.bundle_id
                    AND (
                      bundle_peer.state <> 'EXPIRED'
                      OR bundle_peer.hub_session_id IS NOT offerer.hub_session_id
                      OR bundle_peer.lineage_id IS NOT offerer.lineage_id
                      OR bundle_peer.incarnation IS NOT offerer.incarnation
                      OR bundle_peer.terminal_at IS NOT offerer.terminal_at
                      OR bundle_peer.terminal_reason IS NOT offerer.terminal_reason
                    )
                ))
              OR (offerer.state = 'ACTIVE'
                AND unixepoch(offerer.expires_at) <= unixepoch(NEW.created_at)
                AND NOT EXISTS (
                  SELECT 1 FROM adapter_session_tickets bundle_peer
                  WHERE bundle_peer.bundle_id = offerer.bundle_id
                    AND (
                      bundle_peer.state <> 'ACTIVE'
                      OR bundle_peer.hub_session_id IS NOT offerer.hub_session_id
                      OR bundle_peer.lineage_id IS NOT offerer.lineage_id
                      OR bundle_peer.incarnation IS NOT offerer.incarnation
                      OR bundle_peer.expires_at IS NOT offerer.expires_at
                      OR bundle_peer.activated_at IS NOT offerer.activated_at
                      OR bundle_peer.terminal_at IS NOT NULL
                      OR bundle_peer.terminal_reason IS NOT NULL
                    )
                ))
            )
            AND (
              SELECT COUNT(*) = CASE offerer.session_client
                       WHEN 'codex-app-server' THEN 3 WHEN 'codex-cli-hooks' THEN 2
                       WHEN 'claude-channel' THEN 1 WHEN 'claude-hooks' THEN 2 END
                AND SUM(bundle_member.purpose = 'CONTROL') = 1
                AND SUM(bundle_member.purpose = 'MODEL_MCP') =
                  CASE WHEN offerer.session_client = 'codex-app-server' THEN 1 ELSE 0 END
                AND SUM(bundle_member.purpose = 'CAPTURE') =
                  CASE WHEN offerer.session_client IN ('codex-cli-hooks', 'claude-hooks') THEN 1 ELSE 0 END
                AND SUM(bundle_member.purpose = 'INJECTOR') =
                  CASE WHEN offerer.session_client = 'codex-app-server' THEN 1 ELSE 0 END
              FROM adapter_session_tickets bundle_member
              WHERE bundle_member.bundle_id = offerer.bundle_id
            )
          )
        )
        AND offerer.project_id = NEW.project_id
        AND offerer.adapter_client = NEW.adapter_client
        AND offerer.agent_id = NEW.agent_id
        AND offerer.session_client = NEW.session_client
        AND offerer.role = NEW.role
        AND offerer.transport = NEW.transport
        AND offerer.delivery_mode = NEW.delivery_mode
        AND offerer.external_session_id IS NEW.external_session_id
        AND offerer.external_thread_id IS NEW.external_thread_id
        AND offerer.lineage_id = NEW.expected_lineage_id
        AND offerer.hub_session_id = NEW.expected_head_session_id
        AND session.id = lineage.head_session_id
        AND session.incarnation = offerer.incarnation
        AND session.connection_state <> 'CLOSED'
    )
  )
)
BEGIN
  SELECT RAISE(ABORT, 'TICKET_OFFER_NOT_AUTHORIZED');
END;

CREATE TRIGGER adapter_session_tickets_immutable_update
BEFORE UPDATE ON adapter_session_tickets
WHEN NOT (
  OLD.id = NEW.id
  AND OLD.bundle_id = NEW.bundle_id
  AND OLD.purpose = NEW.purpose
  AND OLD.token_sha256 = NEW.token_sha256
  AND OLD.offered_by_auth_credential_id IS NEW.offered_by_auth_credential_id
  AND OLD.offered_by_ticket_id IS NEW.offered_by_ticket_id
  AND OLD.project_id = NEW.project_id
  AND OLD.adapter_client = NEW.adapter_client
  AND OLD.agent_id = NEW.agent_id
  AND OLD.session_client = NEW.session_client
  AND OLD.role = NEW.role
  AND OLD.transport = NEW.transport
  AND OLD.delivery_mode = NEW.delivery_mode
  AND OLD.external_session_id IS NEW.external_session_id
  AND OLD.external_thread_id IS NEW.external_thread_id
  AND OLD.run_id = NEW.run_id
  AND OLD.activation_mode = NEW.activation_mode
  AND OLD.expected_lineage_id IS NEW.expected_lineage_id
  AND OLD.expected_head_session_id IS NEW.expected_head_session_id
  AND OLD.launch_reservation_id IS NEW.launch_reservation_id
  AND OLD.idempotency_key = NEW.idempotency_key
  AND OLD.request_sha256 = NEW.request_sha256
  AND OLD.offer_expires_at = NEW.offer_expires_at
  AND OLD.created_at = NEW.created_at
  AND (
    (OLD.state = 'PENDING' AND NEW.state = 'ACTIVE'
      AND OLD.hub_session_id IS NULL AND OLD.lineage_id IS NULL AND OLD.incarnation IS NULL
      AND NEW.hub_session_id IS NOT NULL AND NEW.lineage_id IS NOT NULL
      AND NEW.incarnation IS NOT NULL AND NEW.expires_at IS NOT NULL
      AND NEW.activated_at IS NOT NULL
      AND NEW.terminal_at IS NULL AND NEW.terminal_reason IS NULL)
    OR (OLD.state IN ('PENDING', 'ACTIVE')
      AND NEW.state IN ('REVOKED', 'EXPIRED', 'SUPERSEDED')
      AND OLD.hub_session_id IS NEW.hub_session_id
      AND OLD.lineage_id IS NEW.lineage_id
      AND OLD.incarnation IS NEW.incarnation
      AND OLD.expires_at IS NEW.expires_at
      AND OLD.activated_at IS NEW.activated_at
      AND NEW.terminal_at IS NOT NULL AND NEW.terminal_reason IS NOT NULL)
  )
)
BEGIN
  SELECT RAISE(ABORT, 'adapter session tickets are immutable except activation or terminalization');
END;

CREATE TRIGGER adapter_session_tickets_activation_consistency_guard
BEFORE UPDATE OF state ON adapter_session_tickets
WHEN OLD.state = 'PENDING' AND NEW.state = 'ACTIVE' AND NOT EXISTS (
  SELECT 1
  FROM agent_sessions session
  JOIN session_lineages lineage ON lineage.id = session.lineage_id
  WHERE session.id = NEW.hub_session_id
    AND session.project_id = NEW.project_id
    AND session.agent_id = NEW.agent_id
    AND session.client = NEW.session_client
    AND session.role = NEW.role
    AND session.transport = NEW.transport
    AND session.delivery_mode = NEW.delivery_mode
    AND session.external_session_id IS NEW.external_session_id
    AND session.external_thread_id IS NEW.external_thread_id
    AND session.connection_state <> 'CLOSED'
    AND session.lineage_id = NEW.lineage_id
    AND session.incarnation = NEW.incarnation
    AND session.launcher_run_id = NEW.run_id
    AND lineage.id = NEW.lineage_id
    AND lineage.project_id = NEW.project_id
    AND lineage.agent_id = NEW.agent_id
    AND lineage.client = NEW.session_client
    AND lineage.head_session_id = session.id
    AND lineage.head_incarnation = NEW.incarnation
    AND (
      SELECT COUNT(*) FROM adapter_session_tickets bundle_member
      WHERE bundle_member.bundle_id = NEW.bundle_id
    ) = CASE NEW.session_client
      WHEN 'codex-app-server' THEN 3
      WHEN 'codex-cli-hooks' THEN 2
      WHEN 'claude-channel' THEN 1
      WHEN 'claude-hooks' THEN 2
    END
    AND EXISTS (
      SELECT 1 FROM adapter_session_tickets control_member
      WHERE control_member.bundle_id = NEW.bundle_id AND control_member.purpose = 'CONTROL'
    )
    AND (
      NEW.session_client <> 'codex-app-server'
      OR EXISTS (
        SELECT 1 FROM adapter_session_tickets model_member
        WHERE model_member.bundle_id = NEW.bundle_id AND model_member.purpose = 'MODEL_MCP'
      )
    )
    AND (
      NEW.session_client <> 'codex-app-server'
      OR EXISTS (
        SELECT 1 FROM adapter_session_tickets injector_member
        WHERE injector_member.bundle_id = NEW.bundle_id AND injector_member.purpose = 'INJECTOR'
      )
    )
    AND (
      NEW.session_client NOT IN ('codex-cli-hooks', 'claude-hooks')
      OR EXISTS (
        SELECT 1 FROM adapter_session_tickets capture_member
        WHERE capture_member.bundle_id = NEW.bundle_id AND capture_member.purpose = 'CAPTURE'
      )
    )
    AND NOT EXISTS (
      SELECT 1 FROM adapter_session_tickets peer
      WHERE peer.bundle_id = NEW.bundle_id
        AND (
          peer.state NOT IN ('PENDING', 'ACTIVE')
          OR peer.project_id <> NEW.project_id
          OR peer.adapter_client <> NEW.adapter_client
          OR peer.agent_id <> NEW.agent_id
          OR peer.session_client <> NEW.session_client
          OR peer.role <> NEW.role
          OR peer.transport <> NEW.transport
          OR peer.delivery_mode <> NEW.delivery_mode
          OR peer.external_session_id IS NOT NEW.external_session_id
          OR peer.external_thread_id IS NOT NEW.external_thread_id
          OR peer.run_id <> NEW.run_id
          OR peer.activation_mode <> NEW.activation_mode
          OR peer.expected_lineage_id IS NOT NEW.expected_lineage_id
          OR peer.expected_head_session_id IS NOT NEW.expected_head_session_id
          OR peer.launch_reservation_id IS NOT NEW.launch_reservation_id
        )
    )
    AND (
      (NEW.activation_mode = 'FIRST_LINEAGE'
        AND session.predecessor_session_id IS NULL
        AND session.incarnation = 1
        AND EXISTS (
          SELECT 1 FROM adapter_session_tickets control
          WHERE control.bundle_id = NEW.bundle_id AND control.purpose = 'CONTROL'
            AND control.state IN ('PENDING', 'ACTIVE')
            AND control.offered_by_auth_credential_id = 'crd_agent_' || NEW.adapter_client
        ))
      OR (NEW.activation_mode = 'CURRENT_HEAD_REPLACEMENT'
        AND session.predecessor_session_id = NEW.expected_head_session_id
        AND NEW.expected_lineage_id = session.lineage_id
        AND EXISTS (
          SELECT 1
          FROM adapter_session_tickets control_offer
          JOIN adapter_session_tickets prior_control
            ON prior_control.id = control_offer.offered_by_ticket_id
          JOIN agent_sessions predecessor
            ON predecessor.id = prior_control.hub_session_id
          WHERE control_offer.bundle_id = NEW.bundle_id
            AND control_offer.purpose = 'CONTROL'
            AND prior_control.purpose = 'CONTROL'
            AND prior_control.hub_session_id = NEW.expected_head_session_id
            AND prior_control.lineage_id = NEW.expected_lineage_id
            AND prior_control.project_id = NEW.project_id
            AND prior_control.adapter_client = NEW.adapter_client
            AND prior_control.agent_id = NEW.agent_id
            AND prior_control.session_client = NEW.session_client
            AND prior_control.role = NEW.role
            AND prior_control.transport = NEW.transport
            AND prior_control.delivery_mode = NEW.delivery_mode
            AND prior_control.external_session_id IS NEW.external_session_id
            AND prior_control.external_thread_id IS NEW.external_thread_id
            AND predecessor.project_id = prior_control.project_id
            AND predecessor.agent_id = prior_control.agent_id
            AND predecessor.client = prior_control.session_client
            AND predecessor.role = prior_control.role
            AND predecessor.transport = prior_control.transport
            AND predecessor.delivery_mode = prior_control.delivery_mode
            AND predecessor.external_session_id IS prior_control.external_session_id
            AND predecessor.external_thread_id IS prior_control.external_thread_id
            AND predecessor.connection_state <> 'CLOSED'
            AND predecessor.lineage_id = prior_control.lineage_id
            AND predecessor.incarnation = prior_control.incarnation
            AND session.incarnation = predecessor.incarnation + 1
            AND NOT EXISTS (
              SELECT 1 FROM adapter_session_tickets dynamic_offer
              WHERE dynamic_offer.bundle_id = NEW.bundle_id
                AND dynamic_offer.offered_by_ticket_id IS NOT NULL
                AND dynamic_offer.offered_by_ticket_id <> prior_control.id
            )
            AND (
              (prior_control.state = 'ACTIVE'
                AND unixepoch(prior_control.expires_at) > unixepoch(NEW.activated_at))
              OR (prior_control.state = 'EXPIRED'
                AND prior_control.terminal_at IS NOT NULL
                AND prior_control.terminal_reason IS NOT NULL
                AND NOT EXISTS (
                  SELECT 1 FROM adapter_session_tickets prior_peer
                  WHERE prior_peer.bundle_id = prior_control.bundle_id
                    AND (
                      prior_peer.state <> 'EXPIRED'
                      OR prior_peer.hub_session_id IS NOT prior_control.hub_session_id
                      OR prior_peer.lineage_id IS NOT prior_control.lineage_id
                      OR prior_peer.incarnation IS NOT prior_control.incarnation
                      OR prior_peer.terminal_at IS NOT prior_control.terminal_at
                      OR prior_peer.terminal_reason IS NOT prior_control.terminal_reason
                    )
                ))
              OR (prior_control.state = 'ACTIVE'
                AND unixepoch(prior_control.expires_at) <= unixepoch(NEW.activated_at)
                AND NOT EXISTS (
                  SELECT 1 FROM adapter_session_tickets prior_peer
                  WHERE prior_peer.bundle_id = prior_control.bundle_id
                    AND (
                      prior_peer.state <> 'ACTIVE'
                      OR prior_peer.hub_session_id IS NOT prior_control.hub_session_id
                      OR prior_peer.lineage_id IS NOT prior_control.lineage_id
                      OR prior_peer.incarnation IS NOT prior_control.incarnation
                      OR prior_peer.expires_at IS NOT prior_control.expires_at
                      OR prior_peer.activated_at IS NOT prior_control.activated_at
                      OR prior_peer.terminal_at IS NOT NULL
                      OR prior_peer.terminal_reason IS NOT NULL
                    )
                ))
            )
            AND (
              SELECT COUNT(*) = CASE prior_control.session_client
                       WHEN 'codex-app-server' THEN 3 WHEN 'codex-cli-hooks' THEN 2
                       WHEN 'claude-channel' THEN 1 WHEN 'claude-hooks' THEN 2 END
                AND SUM(prior_member.purpose = 'CONTROL') = 1
                AND SUM(prior_member.purpose = 'MODEL_MCP') =
                  CASE WHEN prior_control.session_client = 'codex-app-server' THEN 1 ELSE 0 END
                AND SUM(prior_member.purpose = 'CAPTURE') =
                  CASE WHEN prior_control.session_client IN ('codex-cli-hooks', 'claude-hooks') THEN 1 ELSE 0 END
                AND SUM(prior_member.purpose = 'INJECTOR') =
                  CASE WHEN prior_control.session_client = 'codex-app-server' THEN 1 ELSE 0 END
              FROM adapter_session_tickets prior_member
              WHERE prior_member.bundle_id = prior_control.bundle_id
            )
        ))
      OR (NEW.activation_mode = 'MANAGED_RESERVATION'
        AND session.predecessor_session_id IS NEW.expected_head_session_id
        AND NEW.expected_lineage_id = session.lineage_id
        AND EXISTS (
          SELECT 1 FROM session_launch_reservations reservation
          WHERE reservation.id = NEW.launch_reservation_id
            AND reservation.project_id = NEW.project_id
            AND reservation.lineage_id = NEW.expected_lineage_id
            AND reservation.run_id = NEW.run_id
            AND reservation.expected_head_session_id IS NEW.expected_head_session_id
            AND reservation.state = 'CONSUMED'
            AND reservation.consumed_session_id = session.id
        ))
      OR (NEW.activation_mode = 'SESSION_AUXILIARY'
        AND NEW.expected_lineage_id = session.lineage_id
        AND NEW.expected_head_session_id = session.id
        AND EXISTS (
          SELECT 1
          FROM adapter_session_tickets control_offer
          JOIN adapter_session_tickets prior_control
            ON prior_control.id = control_offer.offered_by_ticket_id
          WHERE control_offer.bundle_id = NEW.bundle_id
            AND control_offer.purpose = 'CONTROL'
            AND prior_control.purpose = 'CONTROL' AND prior_control.state = 'ACTIVE'
            AND unixepoch(prior_control.expires_at) > unixepoch(NEW.activated_at)
            AND prior_control.hub_session_id = session.id
            AND prior_control.lineage_id = session.lineage_id
            AND prior_control.incarnation = session.incarnation
            AND prior_control.project_id = NEW.project_id
            AND prior_control.adapter_client = NEW.adapter_client
            AND prior_control.agent_id = NEW.agent_id
            AND prior_control.session_client = NEW.session_client
            AND prior_control.role = NEW.role
            AND prior_control.transport = NEW.transport
            AND prior_control.delivery_mode = NEW.delivery_mode
            AND prior_control.external_session_id IS NEW.external_session_id
            AND prior_control.external_thread_id IS NEW.external_thread_id
        ))
    )
)
BEGIN
  SELECT RAISE(ABORT, 'TICKET_BINDING_MISMATCH');
END;

CREATE TRIGGER adapter_session_tickets_immutable_delete
BEFORE DELETE ON adapter_session_tickets
BEGIN
  SELECT RAISE(ABORT, 'adapter session tickets cannot be deleted');
END;

-- Existing v7 provenance keeps the static credential that offered a ticket and gains the exact
-- dynamic ticket that exercised the capability. Legacy rows remain nullable; every new row is
-- guarded below and must carry a live, session-bound purpose ticket.
ALTER TABLE capture_session_bindings
  ADD COLUMN session_ticket_id TEXT REFERENCES adapter_session_tickets(id) ON DELETE RESTRICT;
ALTER TABLE synthetic_prompt_reservations
  ADD COLUMN session_ticket_id TEXT REFERENCES adapter_session_tickets(id) ON DELETE RESTRICT;
ALTER TABLE user_turns
  ADD COLUMN source_session_ticket_id TEXT REFERENCES adapter_session_tickets(id) ON DELETE RESTRICT;
ALTER TABLE user_turn_capture_receipts
  ADD COLUMN session_ticket_id TEXT REFERENCES adapter_session_tickets(id) ON DELETE RESTRICT;

CREATE INDEX idx_capture_session_bindings_ticket
  ON capture_session_bindings(session_ticket_id, revoked_at);
CREATE INDEX idx_synthetic_prompt_reservations_ticket
  ON synthetic_prompt_reservations(session_ticket_id, state);
CREATE INDEX idx_user_turns_source_ticket
  ON user_turns(source_session_ticket_id, received_at);
CREATE INDEX idx_user_turn_capture_receipts_ticket
  ON user_turn_capture_receipts(session_ticket_id, created_at);

DROP TRIGGER capture_session_bindings_authority_guard;
CREATE TRIGGER capture_session_bindings_authority_guard
BEFORE INSERT ON capture_session_bindings
WHEN NEW.session_ticket_id IS NULL OR NOT EXISTS (
  SELECT 1
  FROM adapter_session_tickets ticket
  JOIN auth_principals principal ON principal.id = NEW.principal_id
  JOIN auth_credentials credential ON credential.id = NEW.credential_id
  JOIN agent_sessions session ON session.id = NEW.hub_session_id
  JOIN session_lineages lineage ON lineage.id = session.lineage_id
  WHERE ticket.id = NEW.session_ticket_id
    AND ticket.purpose = 'CAPTURE' AND ticket.state = 'ACTIVE'
    AND unixepoch(ticket.expires_at) > unixepoch(NEW.created_at)
    AND ticket.offered_by_auth_credential_id = NEW.credential_id
    AND ticket.project_id = NEW.project_id
    AND ticket.adapter_client = NEW.client_type AND ticket.agent_id = NEW.client_type
    AND ticket.hub_session_id = NEW.hub_session_id
    AND ticket.lineage_id = session.lineage_id AND ticket.incarnation = session.incarnation
    AND principal.id = 'prn_capture_' || NEW.client_type
    AND principal.kind = 'BRIDGE_CAPTURE' AND principal.status = 'ACTIVE'
    AND principal.client_type = NEW.client_type
    AND credential.principal_id = principal.id AND credential.revoked_at IS NULL
    AND (credential.expires_at IS NULL
      OR unixepoch(credential.expires_at) > unixepoch(NEW.created_at))
    AND session.project_id = NEW.project_id AND session.agent_id = NEW.client_type
    AND session.client = CASE NEW.client_type
      WHEN 'codex' THEN 'codex-cli-hooks'
      WHEN 'claude' THEN 'claude-hooks'
    END
    AND session.connection_state <> 'CLOSED'
    AND session.external_session_id = NEW.source_session_id
    AND lineage.head_session_id = session.id AND lineage.head_incarnation = session.incarnation
)
BEGIN
  SELECT RAISE(ABORT, 'capture session binding is not authorized for session ticket');
END;

DROP TRIGGER capture_session_bindings_restricted_update;
CREATE TRIGGER capture_session_bindings_restricted_update
BEFORE UPDATE ON capture_session_bindings
WHEN NOT (
  OLD.project_id = NEW.project_id AND OLD.principal_id = NEW.principal_id
  AND OLD.credential_id = NEW.credential_id AND OLD.session_ticket_id IS NEW.session_ticket_id
  AND OLD.client_type = NEW.client_type AND OLD.source_session_id = NEW.source_session_id
  AND OLD.hub_session_id = NEW.hub_session_id AND OLD.created_at = NEW.created_at
  AND OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'capture session bindings are immutable except for revocation');
END;

DROP TRIGGER synthetic_prompt_reservations_authority_guard;
CREATE TRIGGER synthetic_prompt_reservations_authority_guard
BEFORE INSERT ON synthetic_prompt_reservations
WHEN NEW.session_ticket_id IS NULL OR NOT EXISTS (
  SELECT 1
  FROM adapter_session_tickets injector_ticket
  JOIN auth_principals injector ON injector.id = NEW.principal_id
  JOIN auth_credentials credential ON credential.id = NEW.credential_id
  JOIN agent_sessions session ON session.id = NEW.injector_hub_session_id
  JOIN session_lineages lineage ON lineage.id = session.lineage_id
  JOIN messages message ON message.id = NEW.source_message_id
  JOIN message_surface_attempts surface ON surface.id = NEW.surface_attempt_id
  JOIN message_recipients recipient ON recipient.id = surface.recipient_id
  JOIN auth_principals capture ON capture.id = NEW.capture_principal_id
  JOIN capture_session_bindings binding ON binding.id = NEW.capture_binding_id
  JOIN adapter_session_tickets capture_ticket ON capture_ticket.id = binding.session_ticket_id
  JOIN agent_sessions capture_session ON capture_session.id = binding.hub_session_id
  JOIN session_lineages capture_lineage ON capture_lineage.id = capture_session.lineage_id
  WHERE injector_ticket.id = NEW.session_ticket_id
    AND injector_ticket.purpose = 'INJECTOR' AND injector_ticket.state = 'ACTIVE'
    AND unixepoch(injector_ticket.expires_at) > unixepoch(NEW.prepared_at)
    AND injector_ticket.offered_by_auth_credential_id = NEW.credential_id
    AND injector_ticket.project_id = NEW.project_id
    AND injector_ticket.adapter_client = NEW.client_type
    AND injector_ticket.hub_session_id = NEW.injector_hub_session_id
    AND injector_ticket.lineage_id = session.lineage_id
    AND injector_ticket.incarnation = session.incarnation
    AND injector.id = 'prn_inject_' || NEW.client_type
    AND injector.kind = 'BRIDGE_INJECTOR' AND injector.status = 'ACTIVE'
    AND injector.client_type = NEW.client_type
    AND credential.principal_id = injector.id AND credential.revoked_at IS NULL
    AND (credential.expires_at IS NULL
      OR unixepoch(credential.expires_at) > unixepoch(NEW.prepared_at))
    AND session.project_id = NEW.project_id AND session.agent_id = NEW.client_type
    AND session.client = NEW.client_type || '-app-server'
    AND session.connection_state <> 'CLOSED'
    AND session.external_session_id = NEW.external_session_id
    AND lineage.head_session_id = session.id AND lineage.head_incarnation = session.incarnation
    AND message.project_id = NEW.project_id
    AND surface.message_id = NEW.source_message_id
    AND surface.session_id = NEW.injector_hub_session_id
    AND surface.recipient_fence = NEW.recipient_fence AND surface.state = 'ACTIVE'
    AND recipient.message_id = NEW.source_message_id
    AND recipient.recipient_agent_id = NEW.client_type
    AND capture.id = 'prn_capture_' || NEW.client_type
    AND capture.kind = 'BRIDGE_CAPTURE' AND capture.status = 'ACTIVE'
    AND binding.project_id = NEW.project_id
    AND binding.principal_id = NEW.capture_principal_id
    AND binding.client_type = NEW.client_type
    AND binding.source_session_id = NEW.external_session_id
    AND binding.revoked_at IS NULL
    AND capture_ticket.purpose = 'CAPTURE' AND capture_ticket.state = 'ACTIVE'
    AND unixepoch(capture_ticket.expires_at) > unixepoch(NEW.prepared_at)
    AND capture_ticket.project_id = NEW.project_id
    AND capture_ticket.adapter_client = NEW.client_type
    AND capture_ticket.hub_session_id = binding.hub_session_id
    AND capture_ticket.lineage_id = capture_session.lineage_id
    AND capture_ticket.incarnation = capture_session.incarnation
    AND capture_session.project_id = NEW.project_id
    AND capture_session.agent_id = NEW.client_type
    AND capture_session.client = CASE NEW.client_type
      WHEN 'codex' THEN 'codex-cli-hooks'
      WHEN 'claude' THEN 'claude-hooks'
    END
    AND capture_session.connection_state <> 'CLOSED'
    AND capture_session.external_session_id = NEW.external_session_id
    AND capture_lineage.head_session_id = capture_session.id
    AND capture_lineage.head_incarnation = capture_session.incarnation
)
BEGIN
  SELECT RAISE(ABORT, 'synthetic prompt reservation is not authorized for session ticket');
END;

DROP TRIGGER synthetic_prompt_reservations_restricted_update;
CREATE TRIGGER synthetic_prompt_reservations_restricted_update
BEFORE UPDATE ON synthetic_prompt_reservations
WHEN NOT (
  OLD.project_id = NEW.project_id AND OLD.principal_id = NEW.principal_id
  AND OLD.credential_id = NEW.credential_id AND OLD.session_ticket_id IS NEW.session_ticket_id
  AND OLD.capture_principal_id = NEW.capture_principal_id
  AND OLD.capture_binding_id = NEW.capture_binding_id
  AND OLD.client_type = NEW.client_type
  AND OLD.external_session_id = NEW.external_session_id
  AND OLD.injector_hub_session_id = NEW.injector_hub_session_id
  AND OLD.source_message_id = NEW.source_message_id
  AND OLD.surface_attempt_id = NEW.surface_attempt_id
  AND OLD.recipient_fence = NEW.recipient_fence AND OLD.rpc_method = NEW.rpc_method
  AND OLD.origin_nonce = NEW.origin_nonce AND OLD.raw_text = NEW.raw_text
  AND OLD.raw_text_sha256 = NEW.raw_text_sha256
  AND OLD.prepared_at = NEW.prepared_at AND OLD.expires_at = NEW.expires_at
  AND OLD.idempotency_key = NEW.idempotency_key AND OLD.request_sha256 = NEW.request_sha256
  AND OLD.correlation_id IS NEW.correlation_id AND OLD.created_at = NEW.created_at
  AND (
    (OLD.state = 'PREPARED' AND NEW.state = 'CONSUMED'
      AND OLD.consumed_at IS NULL AND NEW.consumed_at IS NOT NULL
      AND OLD.aborted_at IS NULL AND NEW.aborted_at IS NULL)
    OR (OLD.state = 'PREPARED' AND NEW.state = 'ABORTED'
      AND OLD.aborted_at IS NULL AND NEW.aborted_at IS NOT NULL
      AND OLD.consumed_at IS NULL AND NEW.consumed_at IS NULL)
  )
)
BEGIN
  SELECT RAISE(ABORT, 'synthetic prompt reservations only permit one terminal transition');
END;

DROP TRIGGER user_turns_capture_binding_guard;
CREATE TRIGGER user_turns_capture_binding_guard
BEFORE INSERT ON user_turns
WHEN NEW.source_session_ticket_id IS NULL OR NOT EXISTS (
  SELECT 1
  FROM capture_session_bindings binding
  JOIN adapter_session_tickets ticket ON ticket.id = NEW.source_session_ticket_id
  JOIN auth_principals principal ON principal.id = binding.principal_id
  JOIN auth_credentials credential ON credential.id = binding.credential_id
  JOIN agent_sessions session ON session.id = binding.hub_session_id
  JOIN session_lineages lineage ON lineage.id = session.lineage_id
  WHERE binding.id = NEW.source_binding_id
    AND binding.project_id = NEW.project_id
    AND binding.principal_id = NEW.source_principal_id
    AND binding.credential_id = NEW.source_credential_id
    AND binding.session_ticket_id = NEW.source_session_ticket_id
    AND binding.client_type = NEW.client_type
    AND binding.source_session_id = NEW.source_session_id
    AND binding.hub_session_id = NEW.source_hub_session_id
    AND binding.revoked_at IS NULL
    AND ticket.purpose = 'CAPTURE' AND ticket.state = 'ACTIVE'
    AND unixepoch(ticket.expires_at) > unixepoch(NEW.received_at)
    AND ticket.project_id = NEW.project_id AND ticket.adapter_client = NEW.client_type
    AND ticket.hub_session_id = NEW.source_hub_session_id
    AND ticket.lineage_id = session.lineage_id AND ticket.incarnation = session.incarnation
    AND principal.id = 'prn_capture_' || NEW.client_type
    AND principal.kind = 'BRIDGE_CAPTURE' AND principal.status = 'ACTIVE'
    AND credential.principal_id = principal.id AND credential.revoked_at IS NULL
    AND session.project_id = NEW.project_id AND session.agent_id = NEW.client_type
    AND session.external_session_id = NEW.source_session_id
    AND session.connection_state <> 'CLOSED'
    AND lineage.head_session_id = session.id AND lineage.head_incarnation = session.incarnation
)
BEGIN
  SELECT RAISE(ABORT, 'user_turn capture is not authorized for session ticket');
END;

DROP TRIGGER user_turn_capture_receipts_authority_guard;
CREATE TRIGGER user_turn_capture_receipts_authority_guard
BEFORE INSERT ON user_turn_capture_receipts
WHEN NEW.session_ticket_id IS NULL OR NOT EXISTS (
  SELECT 1
  FROM capture_session_bindings binding
  JOIN adapter_session_tickets ticket ON ticket.id = NEW.session_ticket_id
  WHERE binding.id = NEW.binding_id
    AND binding.principal_id = NEW.principal_id
    AND binding.credential_id = NEW.credential_id
    AND binding.session_ticket_id = NEW.session_ticket_id
    AND binding.revoked_at IS NULL
    AND ticket.purpose = 'CAPTURE' AND ticket.state = 'ACTIVE'
    AND unixepoch(ticket.expires_at) > unixepoch(NEW.created_at)
    AND ticket.project_id = binding.project_id
    AND ticket.adapter_client = binding.client_type
    AND ticket.hub_session_id = binding.hub_session_id
    AND (
      (NEW.status = 'CAPTURED' AND EXISTS (
        SELECT 1 FROM user_turns turn
        WHERE turn.id = NEW.user_turn_id
          AND turn.source_principal_id = NEW.principal_id
          AND turn.source_credential_id = NEW.credential_id
          AND turn.source_session_ticket_id = NEW.session_ticket_id
          AND turn.source_binding_id = NEW.binding_id
      ))
      OR (NEW.status = 'EXCLUDED' AND EXISTS (
        SELECT 1 FROM synthetic_prompt_reservations reservation
        WHERE reservation.id = NEW.synthetic_reservation_id
          AND reservation.capture_principal_id = NEW.principal_id
          AND reservation.capture_binding_id = NEW.binding_id
          AND reservation.project_id = binding.project_id
          AND reservation.client_type = binding.client_type
          AND reservation.external_session_id = binding.source_session_id
          AND reservation.state = 'CONSUMED'
      ))
    )
)
BEGIN
  SELECT RAISE(ABORT, 'user-turn receipt provenance is not authorized for session ticket');
END;

-- Signed user authority must name the exact live relay session. The static Agent principal remains
-- the durable actor identity, while the CONTROL ticket proves the active session incarnation.
CREATE TRIGGER authority_directives_session_ticket_guard
BEFORE INSERT ON authority_directives
WHEN NEW.authority IN ('USER_ATTESTED', 'USER_DELEGATED')
AND NOT (
  NEW.authority = 'USER_ATTESTED'
  AND NEW.relay_session_id IS NULL
  AND NEW.supersedes_directive_id IS NOT NULL
  AND NEW.causation_id = NEW.supersedes_directive_id
  AND EXISTS (
    SELECT 1
    FROM authority_directives predecessor
    JOIN authority_events supersede_event
      ON supersede_event.directive_id = predecessor.id
    JOIN auth_principals dashboard
      ON dashboard.id = supersede_event.actor_principal_id
    JOIN events issuance_event
      ON issuance_event.project_id = NEW.project_id
      AND issuance_event.sequence = NEW.server_sequence
    WHERE predecessor.id = NEW.supersedes_directive_id
      AND predecessor.project_id = NEW.project_id
      AND supersede_event.event_type = 'SUPERSEDED'
      AND supersede_event.actor_session_id IS NULL
      AND supersede_event.causation_id = NEW.id
      AND supersede_event.correlation_id = NEW.correlation_id
      AND dashboard.kind = 'DASHBOARD_USER' AND dashboard.status = 'ACTIVE'
      AND issuance_event.type = 'directive.issued'
      AND issuance_event.aggregate_type = 'authority_directive'
      AND issuance_event.aggregate_id = NEW.id
      AND issuance_event.actor_type = 'user'
      AND issuance_event.actor_id = dashboard.display_name
      AND issuance_event.causation_id = NEW.supersedes_directive_id
      AND issuance_event.correlation_id = NEW.correlation_id
  )
)
AND (
  NEW.relay_session_id IS NULL OR NOT EXISTS (
    SELECT 1
    FROM adapter_session_tickets ticket
    JOIN agent_sessions session ON session.id = ticket.hub_session_id
    JOIN session_lineages lineage ON lineage.id = ticket.lineage_id
    WHERE ticket.purpose = 'CONTROL' AND ticket.state = 'ACTIVE'
      AND unixepoch(ticket.expires_at) > unixepoch(NEW.issued_at)
      AND ticket.project_id = NEW.project_id
      AND ticket.agent_id = NEW.relay_agent_id
      AND ticket.hub_session_id = NEW.relay_session_id
      AND session.project_id = NEW.project_id
      AND session.agent_id = NEW.relay_agent_id
      AND session.connection_state <> 'CLOSED'
      AND session.lineage_id = ticket.lineage_id
      AND session.incarnation = ticket.incarnation
      AND lineage.head_session_id = session.id
      AND lineage.head_incarnation = session.incarnation
  )
)
BEGIN
  SELECT RAISE(ABORT, 'directive relay lacks an active session ticket');
END;

-- Static Adapter credentials are enrollment/offer capabilities only. They no longer authorize
-- data-plane session, MCP, capture, injector, or relay operations.
DROP TRIGGER auth_credentials_restricted_update;

UPDATE auth_credentials
SET scopes_json = '["project:join","project:select","session-ticket:offer","session:enroll:first"]'
WHERE id IN ('crd_agent_codex', 'crd_agent_claude');

UPDATE auth_credentials
SET scopes_json = '["project:select"]'
WHERE id = 'crd_local_agent';

UPDATE auth_credentials
SET scopes_json = '["session-ticket:offer:capture"]'
WHERE id IN ('crd_capture_codex', 'crd_capture_claude');

UPDATE auth_credentials
SET scopes_json = '["session-ticket:offer:injector"]'
WHERE id IN ('crd_inject_codex', 'crd_inject_claude');

CREATE TRIGGER auth_credentials_restricted_update
BEFORE UPDATE ON auth_credentials
WHEN NOT (
  OLD.principal_id = NEW.principal_id AND OLD.token_sha256 = NEW.token_sha256
  AND OLD.scopes_json = NEW.scopes_json AND OLD.expires_at IS NEW.expires_at
  AND OLD.created_at = NEW.created_at AND OLD.revoked_at IS NULL AND NEW.revoked_at IS NOT NULL
)
BEGIN
  SELECT RAISE(ABORT, 'auth credentials are immutable except for revocation');
END;
